### ISSUE TITLE
Crashplan 4.3.3 client requires slight modification to work

### ISSUE THREAD

**Issue by erkkah** [Hossy/win-crashplan-uiswitcher#1]
Seems like the format of .ui_info has changed slightly to <port>,<guid>,<host>.
Without the host part, the client just hangs on my machine.

Changing the relevant line to

"%_SEDEXE%" -ri.bak "s/([0-9]+),.*/%_SVCPORT%,%_UIINFOGUID%,%_SVCHOST%/" "%_UIINFO%"

solves the issue.

**Comment by Hossy** [comment]
Thanks for the report, @erkkah!  I tried downloading 4.3.3 to test, but it isn't available on their web site (only 4.3.0).  I called CrashPlan Support and opened a ticket, but they're busy and I'm waiting for a response or call back.  When it becomes available, I will definitely test and update the code as needed.  Stay tuned! :-)

**Comment by Hossy** [comment]
I confirmed with CrashPlan that 4.3.3 was accidentally released and they are recommending anyone that received the new version to uninstall it and reinstall 4.3.0.  As such, I'll hold off making this change until an official version is released.

**Comment by erkkah** [comment]
Wow. I had no idea I was running an unsupported version, I mean it
auto-updates afaik.
Thanks, understood. Let's see what happens.

/Erik

Den 22 sep 2015 20:16 skrev "Hossy" notifications@github.com:

**Comment by Hossy** [comment]
Well, I'm reading the release notes and I guess their PR department is going to play it off as a maintenance release. lol

http://support.code42.com/Release_Notes/CrashPlan_For_Home/4.3.0#Maintenance_Update_4.3.3

Also, looks like they are about to release 4.4.0.  The release notes state is was already released on 9/21, but it isn't completely available yet from their web site.
Win32: https://download2.code42.com/installs/win/install/CrashPlan/jre/CrashPlan_4.4.0_Win.exe
Win64: https://download2.code42.com/installs/win/install/CrashPlan/jre/CrashPlan-x64_4.3.0_Win.exe
Mac: https://download2.code42.com/installs/mac/install/CrashPlan/CrashPlan_4.4.0_Mac.dmg
Linux: https://download2.code42.com/installs/linux/install/CrashPlan/CrashPlan_4.4.0_Linux.tgz

http://support.code42.com/Release_Notes/CrashPlan_For_Home/4.4.0

**Comment by Hossy** [comment]
Hi @erkkah, I fixed this issue in v1.4 of UISwapper.  Thanks for calling this out to me.  Looks like CrashPlan ceased using the ui.properties file for target host and is now exclusively using the .ui.info file.  This makes sense because ui.properties is located under Program Files and .ui.info is located in ProgramData.  UAC puts more restrictions on modifying files in Program Files as the design is such that config/data files should not be present in Program Files.  Please let me know if you have any problems.  I'm marking this issue closed.
